(No commit message.)

diff --git a/src/main/bash/gaia/function/ssh b/src/main/bash/gaia/function/ssh
--- a/src/main/bash/gaia/function/ssh
+++ b/src/main/bash/gaia/function/ssh
@@ -10,13 +10,14 @@ ssh-init() {
   local n=$(arg-count $pids)
 
   if [[ $n == 0 ]]; then
+    # Start new agent, provide some output
     echo Starting new \`ssh-agent\` ...
     ssh-agent > ~/.ssh-init
     source ~/.ssh-init
     ssh-add
   elif [[  $n == 1 && -f ~/.ssh-init ]] && grep "SSH_AGENT_PID=$pids;" ~/.ssh-init >/dev/null; then
-    echo Using running \`ssh-agent\` ...
-    source ~/.ssh-init || return 1
+    # Silently reuse existing agent
+    source ~/.ssh-init > /dev/null || return 1
   else
     shell-error-f -r1 $FUNCNAME Found no suitable \`ssh-agent\`: $pids
     return 1
